package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val immersive_primary = Color(0xFFD0BCFF)
val immersive_onPrimary = Color(0xFF381E72)
val immersive_primaryContainer = Color(0xFF4F378B)
val immersive_onPrimaryContainer = Color(0xFFD0BCFF)
val immersive_secondary = Color(0xFFEADDFF)
val immersive_onSecondary = Color(0xFF21005D)
val immersive_secondaryContainer = Color(0xFF4A4458)
val immersive_onSecondaryContainer = Color(0xFFD0BCFF)
val immersive_tertiary = Color(0xFFE8DEF8)
val immersive_onTertiary = Color(0xFF1D192B)
val immersive_tertiaryContainer = Color(0xFF313033)
val immersive_onTertiaryContainer = Color(0xFFD0BCFF)
val immersive_error = Color(0xFFFFB4AB)
val immersive_errorContainer = Color(0xFF93000A)
val immersive_onError = Color(0xFF690005)
val immersive_onErrorContainer = Color(0xFFFFDAD6)
val immersive_background = Color(0xFF1C1B1F)
val immersive_onBackground = Color(0xFFE6E1E5)
val immersive_surface = Color(0xFF1C1B1F)
val immersive_onSurface = Color(0xFFE6E1E5)
val immersive_surfaceVariant = Color(0xFF2B2930) // Using this for cards
val immersive_onSurfaceVariant = Color(0xFFCAC4D0)
val immersive_outline = Color(0xFF49454F)
val immersive_inverseOnSurface = Color(0xFF1C1B1F)
val immersive_inverseSurface = Color(0xFFE6E1E5)
val immersive_inversePrimary = Color(0xFF4F378B)
val immersive_outlineVariant = Color(0xFF49454F)
val immersive_surfaceContainerHighest = Color(0xFF313033)
val immersive_surfaceContainerHigh = Color(0xFF2B2930)
val immersive_surfaceContainer = Color(0xFF2B2930)
val immersive_surfaceContainerLow = Color(0xFF1C1B1F)
val immersive_surfaceContainerLowest = Color(0xFF1C1B1F)
